# Generated by Django 3.1.3 on 2020-12-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0008_auto_20201216_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('bmi', models.CharField(max_length=100)),
                ('current_smoker', models.CharField(max_length=100)),
                ('heart_rate', models.CharField(max_length=100)),
            ],
        ),
    ]
