# Generated by Django 3.1.3 on 2021-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0010_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='bmi',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='heart_rate',
            field=models.IntegerField(max_length=100),
        ),
    ]
