# Generated by Django 3.1.3 on 2021-02-28 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0011_auto_20210228_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='age',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')]),
        ),
        migrations.AlterField(
            model_name='history',
            name='bmi',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='heart_rate',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')]),
        ),
    ]
