# Generated by Django 3.1.3 on 2021-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0012_auto_20210228_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='result',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='current_smoker',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='history',
            name='heart_rate',
            field=models.IntegerField(),
        ),
    ]
